
crawl:

  page:
    tiki-name: "Tiki"
    tiki-base-url: https://tiki.vn/
    tiki-product-api-url: https://tiki.vn/api/personalish/v1/blocks/listings
    tiki-product-api-query-param:
      limit: 300

  opensearch:
    port: 9200
    url: http://localhost
    username:
    password:

  postgres:
    database-url: "postgres://postgres:postgres@localhost:5432/tiki-product?sslmode=disable"
    username: postgres
    password: postgres
    host: "http://localhost"
    port: 5432
    databaseName: "tiki-product"

  file:
    path: F:\GitHub Repositories\Golang Projects\crawl-data-output
    name: tiki-

  logger:
    level: DEBUG
    isAddSource: false
