
crawl:

  tiki-page:
    name: "Tiki"
    base-url: https://tiki.vn/
    product-api-url: https://tiki.vn/api/personalish/v1/blocks/listings
    product-api-query-param:
      limit: 40
  lazada-page:

  datasource:
    opensearch:
      port: 9200
      url: http://localhost
      username:
      password:

    postgres:
      database-url: "postgres://postgres:postgres@localhost:5432/tiki-product?sslmode=disable"
      username: postgres
      password: postgres
      host: "http://localhost"
      port: 5432
      databaseName: "tiki-product"

    file-local:
      path: F:\GitHub Repositories\Golang Projects\crawl-data-output
      name: tiki-

  logger:
    level: DEBUG
    add-source: false
    trace-request: false
    target: ["FILE", "STDOUT", "REMOTE"] # TODO
    file-path:
    file-pattern:
