crawl:

  page:
    name: "Tiki"
    base-url: https://tiki.vn/
    product-api-url: https://tiki.vn/api/personalish/v1/blocks/listings

  opensearch:
    port: 9200
    url: http://localhost
    username:
    password:

  postgres:
    database-url: "postgres://username:password@localhost:5432/database_name?sslmode=disable"
    username:
    password:
    host: "http://localhost"
    port: 5432
    databaseName: "dbname"

  file:
    path:
    name:

  logger:
    level: DEBUG
